/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAssetStoreToken,
  IAssetStoreTokenInterface,
} from "../IAssetStoreToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "assetIdOfToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_svgPart",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_style",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_tag",
        type: "string",
      },
    ],
    name: "generateSVG",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "styles",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAssetStoreToken__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetStoreTokenInterface {
    return new utils.Interface(_abi) as IAssetStoreTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAssetStoreToken {
    return new Contract(address, _abi, signerOrProvider) as IAssetStoreToken;
  }
}
