/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPathDecoder, IPathDecoderInterface } from "../IPathDecoder";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "body",
        type: "bytes",
      },
    ],
    name: "decodePath",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IPathDecoder__factory {
  static readonly abi = _abi;
  static createInterface(): IPathDecoderInterface {
    return new utils.Interface(_abi) as IPathDecoderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPathDecoder {
    return new Contract(address, _abi, signerOrProvider) as IPathDecoder;
  }
}
