/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISVGHelper, ISVGHelperInterface } from "../ISVGHelper";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "int32",
            name: "x",
            type: "int32",
          },
          {
            internalType: "int32",
            name: "y",
            type: "int32",
          },
          {
            internalType: "bool",
            name: "c",
            type: "bool",
          },
          {
            internalType: "int32",
            name: "r",
            type: "int32",
          },
        ],
        internalType: "struct ISVGHelper.Point[]",
        name: "points",
        type: "tuple[]",
      },
    ],
    name: "PathFromPoints",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ISVGHelper__factory {
  static readonly abi = _abi;
  static createInterface(): ISVGHelperInterface {
    return new utils.Interface(_abi) as ISVGHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISVGHelper {
    return new Contract(address, _abi, signerOrProvider) as ISVGHelper;
  }
}
