/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAssetComposerInterface extends ethers.utils.Interface {
  functions: {
    "registerComposition(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "registerComposition",
    values: [
      {
        assetId: BigNumberish;
        provider: string;
        fill: string;
        transform: string;
        stroke: BigNumberish;
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerComposition",
    data: BytesLike
  ): Result;

  events: {
    "CompositionRegistered(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CompositionRegistered"): EventFragment;
}

export type CompositionRegisteredEvent = TypedEvent<
  [string, BigNumber] & { from: string; compositionId: BigNumber }
>;

export class IAssetComposer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetComposerInterface;

  functions: {
    registerComposition(
      _layers: {
        assetId: BigNumberish;
        provider: string;
        fill: string;
        transform: string;
        stroke: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  registerComposition(
    _layers: {
      assetId: BigNumberish;
      provider: string;
      fill: string;
      transform: string;
      stroke: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    registerComposition(
      _layers: {
        assetId: BigNumberish;
        provider: string;
        fill: string;
        transform: string;
        stroke: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "CompositionRegistered(address,uint256)"(
      from?: null,
      compositionId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; compositionId: BigNumber }
    >;

    CompositionRegistered(
      from?: null,
      compositionId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; compositionId: BigNumber }
    >;
  };

  estimateGas: {
    registerComposition(
      _layers: {
        assetId: BigNumberish;
        provider: string;
        fill: string;
        transform: string;
        stroke: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    registerComposition(
      _layers: {
        assetId: BigNumberish;
        provider: string;
        fill: string;
        transform: string;
        stroke: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
