/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAssetProviderRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getProvider(uint256)": FunctionFragment;
    "getProviderId(string)": FunctionFragment;
    "providerCount()": FunctionFragment;
    "registerProvider(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getProvider",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "providerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;

  events: {
    "ProviderRegistered(address,uint256)": EventFragment;
    "ProviderUpdated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProviderRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderUpdated"): EventFragment;
}

export type ProviderRegisteredEvent = TypedEvent<
  [string, BigNumber] & { from: string; _providerId: BigNumber }
>;

export type ProviderUpdatedEvent = TypedEvent<
  [string, BigNumber] & { from: string; _providerId: BigNumber }
>;

export class IAssetProviderRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetProviderRegistryInterface;

  functions: {
    getProvider(
      _providerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string] & {
          key: string;
          name: string;
          provider: string;
        },
        boolean
      ]
    >;

    getProviderId(
      _key: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    providerCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    registerProvider(
      _provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getProvider(
    _providerId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [string, string, string] & {
        key: string;
        name: string;
        provider: string;
      },
      boolean
    ]
  >;

  getProviderId(_key: string, overrides?: CallOverrides): Promise<BigNumber>;

  providerCount(overrides?: CallOverrides): Promise<BigNumber>;

  registerProvider(
    _provider: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getProvider(
      _providerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string] & {
          key: string;
          name: string;
          provider: string;
        },
        boolean
      ]
    >;

    getProviderId(_key: string, overrides?: CallOverrides): Promise<BigNumber>;

    providerCount(overrides?: CallOverrides): Promise<BigNumber>;

    registerProvider(
      _provider: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "ProviderRegistered(address,uint256)"(
      from?: null,
      _providerId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; _providerId: BigNumber }
    >;

    ProviderRegistered(
      from?: null,
      _providerId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; _providerId: BigNumber }
    >;

    "ProviderUpdated(address,uint256)"(
      from?: null,
      _providerId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; _providerId: BigNumber }
    >;

    ProviderUpdated(
      from?: null,
      _providerId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; _providerId: BigNumber }
    >;
  };

  estimateGas: {
    getProvider(
      _providerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProviderId(_key: string, overrides?: CallOverrides): Promise<BigNumber>;

    providerCount(overrides?: CallOverrides): Promise<BigNumber>;

    registerProvider(
      _provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getProvider(
      _providerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProviderId(
      _key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    providerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerProvider(
      _provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
