/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IAssetStoreRegistryInterface extends ethers.utils.Interface {
  functions: {
    "registerAsset((string,string,string,string,address,bytes,tuple[]))": FunctionFragment;
    "registerAssets(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [
      {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAssets",
    values: [
      {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAssets",
    data: BytesLike
  ): Result;

  events: {
    "AssetRegistered(address,uint256)": EventFragment;
    "CategoryAdded(string,string)": EventFragment;
    "GroupAdded(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CategoryAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GroupAdded"): EventFragment;
}

export type AssetRegisteredEvent = TypedEvent<
  [string, BigNumber] & { from: string; assetId: BigNumber }
>;

export type CategoryAddedEvent = TypedEvent<
  [string, string] & { group: string; category: string }
>;

export type GroupAddedEvent = TypedEvent<[string] & { group: string }>;

export class IAssetStoreRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IAssetStoreRegistryInterface;

  functions: {
    registerAsset(
      _assetInfo: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerAssets(
      _assetInfos: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  registerAsset(
    _assetInfo: {
      group: string;
      category: string;
      name: string;
      minter: string;
      soulbound: string;
      metadata: BytesLike;
      parts: { body: BytesLike; color: string }[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerAssets(
    _assetInfos: {
      group: string;
      category: string;
      name: string;
      minter: string;
      soulbound: string;
      metadata: BytesLike;
      parts: { body: BytesLike; color: string }[];
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    registerAsset(
      _assetInfo: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAssets(
      _assetInfos: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssetRegistered(address,uint256)"(
      from?: null,
      assetId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; assetId: BigNumber }
    >;

    AssetRegistered(
      from?: null,
      assetId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; assetId: BigNumber }
    >;

    "CategoryAdded(string,string)"(
      group?: null,
      category?: null
    ): TypedEventFilter<[string, string], { group: string; category: string }>;

    CategoryAdded(
      group?: null,
      category?: null
    ): TypedEventFilter<[string, string], { group: string; category: string }>;

    "GroupAdded(string)"(
      group?: null
    ): TypedEventFilter<[string], { group: string }>;

    GroupAdded(group?: null): TypedEventFilter<[string], { group: string }>;
  };

  estimateGas: {
    registerAsset(
      _assetInfo: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerAssets(
      _assetInfos: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    registerAsset(
      _assetInfo: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerAssets(
      _assetInfos: {
        group: string;
        category: string;
        name: string;
        minter: string;
        soulbound: string;
        metadata: BytesLike;
        parts: { body: BytesLike; color: string }[];
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
