/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ICategorizedAssetProviderInterface extends ethers.utils.Interface {
  functions: {
    "generateSVGPart(uint256)": FunctionFragment;
    "getAssetCountInCategory(string,string)": FunctionFragment;
    "getAssetIdInCategory(string,string,uint32)": FunctionFragment;
    "getCategoryCount(string)": FunctionFragment;
    "getCategoryNameAtIndex(string,uint32)": FunctionFragment;
    "getGroupCount()": FunctionFragment;
    "getGroupNameAtIndex(uint32)": FunctionFragment;
    "getOwner()": FunctionFragment;
    "getProviderInfo()": FunctionFragment;
    "processPayout(uint256)": FunctionFragment;
    "totalSupply()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "generateSVGPart",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetCountInCategory",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetIdInCategory",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCategoryNameAtIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupNameAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProviderInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "generateSVGPart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetCountInCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetIdInCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCategoryNameAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupNameAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProviderInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;

  events: {
    "Payout(string,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Payout"): EventFragment;
}

export type PayoutEvent = TypedEvent<
  [string, BigNumber, string, BigNumber] & {
    providerKey: string;
    assetId: BigNumber;
    to: string;
    amount: BigNumber;
  }
>;

export class ICategorizedAssetProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICategorizedAssetProviderInterface;

  functions: {
    generateSVGPart(
      _assetId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { svgPart: string; tag: string }>;

    getAssetCountInCategory(
      _group: string,
      _category: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getAssetIdInCategory(
      _group: string,
      _category: string,
      _assetIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCategoryCount(
      _group: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getCategoryNameAtIndex(
      _group: string,
      _categoryIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getGroupCount(overrides?: CallOverrides): Promise<[number]>;

    getGroupNameAtIndex(
      _groupIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getOwner(overrides?: CallOverrides): Promise<[string]>;

    getProviderInfo(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string] & {
          key: string;
          name: string;
          provider: string;
        }
      ]
    >;

    processPayout(
      _assetId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  generateSVGPart(
    _assetId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { svgPart: string; tag: string }>;

  getAssetCountInCategory(
    _group: string,
    _category: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getAssetIdInCategory(
    _group: string,
    _category: string,
    _assetIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCategoryCount(_group: string, overrides?: CallOverrides): Promise<number>;

  getCategoryNameAtIndex(
    _group: string,
    _categoryIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getGroupCount(overrides?: CallOverrides): Promise<number>;

  getGroupNameAtIndex(
    _groupIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  getProviderInfo(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & { key: string; name: string; provider: string }
  >;

  processPayout(
    _assetId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    generateSVGPart(
      _assetId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { svgPart: string; tag: string }>;

    getAssetCountInCategory(
      _group: string,
      _category: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getAssetIdInCategory(
      _group: string,
      _category: string,
      _assetIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCategoryCount(
      _group: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getCategoryNameAtIndex(
      _group: string,
      _categoryIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getGroupCount(overrides?: CallOverrides): Promise<number>;

    getGroupNameAtIndex(
      _groupIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    getProviderInfo(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & { key: string; name: string; provider: string }
    >;

    processPayout(
      _assetId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Payout(string,uint256,address,uint256)"(
      providerKey?: null,
      assetId?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { providerKey: string; assetId: BigNumber; to: string; amount: BigNumber }
    >;

    Payout(
      providerKey?: null,
      assetId?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { providerKey: string; assetId: BigNumber; to: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    generateSVGPart(
      _assetId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAssetCountInCategory(
      _group: string,
      _category: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAssetIdInCategory(
      _group: string,
      _category: string,
      _assetIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCategoryCount(
      _group: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCategoryNameAtIndex(
      _group: string,
      _categoryIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGroupCount(overrides?: CallOverrides): Promise<BigNumber>;

    getGroupNameAtIndex(
      _groupIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getProviderInfo(overrides?: CallOverrides): Promise<BigNumber>;

    processPayout(
      _assetId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    generateSVGPart(
      _assetId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetCountInCategory(
      _group: string,
      _category: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetIdInCategory(
      _group: string,
      _category: string,
      _assetIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCategoryCount(
      _group: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCategoryNameAtIndex(
      _group: string,
      _categoryIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGroupCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGroupNameAtIndex(
      _groupIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProviderInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    processPayout(
      _assetId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
